title: Ruhol Raffen
description: [Cheers for stopping by my professional portfolio! I’m a data scientist who’s chuffed to bits about digging into data and turning it into actionable insights. With a solid background in philosophy and a knack for leveraging data to solve real-world conundrums, I’ve honed my skills in various data science methodologies, tools, and tech.]
theme: jekyll-theme-dinky
